name: Build Kivy App for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Puedes cambiar la versión de Python si es necesario

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git
        python -m pip install --upgrade pip
        pip install buildozer
        pip install python-for-android

    - name: Setup environment for buildozer
      run: |
        sudo apt install -y openjdk-8-jdk
        sudo apt install -y libffi-dev
        sudo apt install -y libssl-dev
        sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev
        sudo apt install -y zlib1g-dev

    - name: Build app with Buildozer
      run: |
        buildozer android debug

    - name: Create GitHub release
      id: release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up
      run: |
        rm -rf .buildozer
        
